import "./globals.css";
import { Navigation } from "./components/navigation";
import { ClerkProvider } from '@clerk/nextjs';


export const metadata: Metadata = {
  title: "Welcome To Next.js 15",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <header className="bg-slate-900 text-white p-4 text-center">
          {/*<p>Welcome to Next.js 15 classes</p>*/}
        <Navigation />
        </header>
          {children}
        <footer className="bg-slate-900 text-white p-4 text-center">
          <p>See-Docs & Thenavigo</p>
        </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
